# Makefile

# Compiler and flags
CC = g++
CFLAGS = -Wall -Wextra

# Directories
BUILD_DIR = build

# Source files
SRC_FILES = src/main.c src/request_parser.c src/scan_file.c

all: bd 

bd:
	$(CC) $(SRC_FILES) -o bd.exe $(CFLAGS)